kind: Service
apiVersion: v1
metadata:
  name: javaservice
  labels:
    app: javaservice
spec:
  selector:
    app: javaapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer	
